spring:
  application:
    name: affable-bean-backend
  datasource:
    url: jdbc:mysql://localhost:3306/affable
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8095